//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_source()
        {
            this.tbl_older_news = new HashSet<tbl_older_news>();
            this.tbl_today_news = new HashSet<tbl_today_news>();
        }
    
        public int SourcePK { get; set; }
        public System.Guid guid { get; set; }
        public Nullable<int> CatFK { get; set; }
        public string title { get; set; }
        public string info { get; set; }
        public string feed_url { get; set; }
        public string icon_url { get; set; }
        public bool isnormal { get; set; }
        public bool isgolden { get; set; }
        public bool issuperuser { get; set; }
        public long follower_count { get; set; }
        public System.DateTime indate { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public int addedby { get; set; }
        public Nullable<int> editedby { get; set; }
        public bool bdeleted { get; set; }
        public bool isArgent { get; set; }
        public string sCats { get; set; }
        public string kindlist { get; set; }
        public bool isManual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_older_news> tbl_older_news { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_today_news> tbl_today_news { get; set; }
    }
}
