//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_news_cat
    {
        public int NewCatPK { get; set; }
        public int NewsFK { get; set; }
        public int CatFK { get; set; }
        public Nullable<byte> bdeleted { get; set; }
        public System.DateTime indate { get; set; }
        public int addedby { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_today_news tbl_today_news { get; set; }
    }
}
